name: CI build

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: "1"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg unzip
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Verify Chrome installation
      run: |
        google-chrome --version

    - name: Install ChromeDriver via SeleniumBase
      run: |
        pipenv run seleniumbase install chromedriver
    - name: Run Linter
      run: |
        pipenv run flake8 tests/
    - name: Run Space Formatter
      run: |
        pipenv run black tests/
    - name: Run tests (headless Chrome)
      run: |
        pipenv run pytest tests/test_home.py -n=3 --browser=chrome --headless -v -s --dashboard --html=report/report.html
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: report/
